### ISSUE TITLE
No Longer Works in Blender 5.0

### ISSUE THREAD

**Issue by Evrady** [Pullusb/breakdowner#1]
Attempting to use this add-on in Blender 5.0 returns the following error.

```
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\5.0\scripts\addons\breakdowner-main\__init__.py", line 260, in invoke
    for fc in action.fcurves:
              ^^^^^^^^^^^^^^
AttributeError: 'Action' object has no attribute 'fcurves'
```

Steps to reproduce
1. Open default Blender Scene in Blender 5.0
2. Add key frames to the cube with different transforms
3. Use Shift + E Hotkey

Add-on worked perfectly in Blender 4.5 LTS

Thank you!

**Comment by Pullusb** [comment]
Hi @Evrady,
That's normal considering 5.0 is now using action slot and removed the old API for accessing fcurves.
I'm aware of that changes but thanks for reporting, hard to keep track of all the addon to update :)

When I can get some spare time for this I'll fix it. Can't say when though...
Still happy to know this is still useful to some people.

If you don't see any changes 2 weeks from now, ping again here.
Cheers

**Comment by Pullusb** [comment]
You know what, it's late, but I see this is your first issue ! let's be a bit reactive ^^ I'll try to quick-patch this RN.

**Comment by Pullusb** [comment]
Done. Should be fixed (and retro-compatible with previous version), just download latest.
Feel free to reopen if you have problems with this new 1.1.0 version

Have a nice blend.
S.
